package api

import "net/http"

func (app *App) routes() http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /healthz", app.handleHealth)
	mux.HandleFunc("GET /readyz", app.handleReady)

	mux.HandleFunc("GET /api/v1/system/status", app.handleSystemStatus)
	mux.HandleFunc("GET /api/v1/products", app.handleProductsIndex)
	mux.HandleFunc("POST /api/v1/products/visual-search", app.handleProductVisualSearch)
	mux.HandleFunc("GET /api/v1/products/suggest", app.handleProductsSuggest)
	mux.HandleFunc("POST /api/v1/search/external", app.handleExternalSearch)
	mux.HandleFunc("GET /api/v1/products/{slug}/frequently-bought-together", app.handleProductFrequentlyBoughtTogether)
	mux.HandleFunc("POST /api/v1/products/{slug}/stock-alert", app.handleProductStockAlert)
	mux.HandleFunc("POST /api/v1/products/{slug}/view", app.handleProductView)
	mux.HandleFunc("GET /api/v1/products/{slug}/related", app.handleProductRelated)
	mux.HandleFunc("GET /api/v1/products/{slug}/reviews", app.handleProductReviews)
	mux.HandleFunc("POST /api/v1/products/{slug}/reviews", app.handleProductReviewCreate)
	mux.HandleFunc("GET /api/v1/products/{slug}", app.handleProductShow)
	mux.HandleFunc("GET /api/v1/categories", app.handleCategoriesIndex)
	mux.HandleFunc("GET /api/v1/categories/{slug}", app.handleCategoryShow)
	mux.HandleFunc("GET /api/v1/bootstrap", app.handleMobileBootstrap)
	mux.HandleFunc("GET /api/v1/mobile/bootstrap", app.handleMobileBootstrap)
	mux.HandleFunc("GET /api/v1/mobile/sync", app.handleMobileSync)
	mux.HandleFunc("POST /api/v1/mobile/events", app.handleMobileEvent)
	mux.HandleFunc("POST /api/v1/mobile/device/register", app.handleMobileDeviceRegister)
	mux.HandleFunc("POST /api/v1/mobile/live-activity-tokens", app.handleLiveActivityToken)
	mux.HandleFunc("GET /api/v1/customer/snapshot", app.handleCustomerSnapshot)
	mux.HandleFunc("GET /api/v1/customer/sync-state", app.handleCustomerSyncState)
	mux.HandleFunc("GET /api/v1/customer/dashboard", app.handleCustomerDashboard)
	mux.HandleFunc("GET /api/v1/security/action-token", app.handleActionToken)
	mux.HandleFunc("POST /api/v1/security/action-token", app.handleActionToken)
	mux.HandleFunc("GET /api/v1/shipping/quote", app.handleShippingQuote)
	mux.HandleFunc("POST /api/v1/shipping/quote", app.handleShippingQuote)
	mux.HandleFunc("GET /api/v1/cargo/options", app.handleCargoOptions)
	mux.HandleFunc("POST /api/v1/erp/products/push", app.handleErkurProductPush)

	mux.HandleFunc("GET /api/v1/content/homepage", app.handleHomepage)
	mux.HandleFunc("GET /api/v1/content/navigation", app.handleNavigation)
	mux.HandleFunc("GET /api/v1/content/campaigns", app.handleCampaigns)
	mux.HandleFunc("GET /api/v1/content/campaigns/{slug}", app.handleCampaignShow)
	mux.HandleFunc("GET /api/v1/content/pages", app.handlePages)
	mux.HandleFunc("GET /api/v1/content/pages/{slug}", app.handlePageShow)
	mux.HandleFunc("GET /api/v1/content/marketing", app.handleMarketing)
	mux.HandleFunc("GET /api/v1/content/stories", app.handleStories)
	mux.HandleFunc("POST /api/v1/tracking/consent", app.handleTrackingConsent)
	mux.HandleFunc("POST /api/v1/tracking/events", app.handleTrackingEvent)
	mux.HandleFunc("POST /api/v1/support/conversations", app.handleSupportConversationCreate)
	mux.HandleFunc("GET /api/v1/support/conversations/{id}/messages", app.handleSupportMessages)
	mux.HandleFunc("POST /api/v1/support/conversations/{id}/messages", app.handleSupportMessageCreate)
	mux.HandleFunc("GET /api/v1/support/conversations/{id}/stream", app.handleSupportStream)

	mux.HandleFunc("POST /api/v1/auth/register", app.handleRegister)
	mux.HandleFunc("POST /api/v1/auth/login", app.handleLogin)
	mux.HandleFunc("GET /api/v1/auth/me", app.handleMe)
	mux.HandleFunc("PUT /api/v1/auth/profile", app.handleProfileUpdate)
	mux.HandleFunc("PATCH /api/v1/auth/profile", app.handleProfileUpdate)
	mux.HandleFunc("POST /api/v1/auth/logout", app.handleLogout)
	mux.HandleFunc("GET /api/v1/auth/providers", app.handleProviders)

	mux.HandleFunc("GET /api/v1/cart", app.handleCartShow)
	mux.HandleFunc("POST /api/v1/cart/items", app.handleCartAdd)
	mux.HandleFunc("PATCH /api/v1/cart/items/{id}", app.handleCartUpdate)
	mux.HandleFunc("DELETE /api/v1/cart/items/{id}", app.handleCartDelete)
	mux.HandleFunc("DELETE /api/v1/cart", app.handleCartClear)
	mux.HandleFunc("POST /api/v1/cart/coupon", app.handleCouponApply)
	mux.HandleFunc("DELETE /api/v1/cart/coupon", app.handleCouponRemove)

	mux.HandleFunc("POST /api/v1/c", app.paymentGuard(app.handleCheckout))
	mux.HandleFunc("POST /api/cb/p", app.handlePayTRCallback)

	mux.HandleFunc("GET /api/v1/orders", app.handleOrdersIndex)
	mux.HandleFunc("GET /api/v1/orders/{id}", app.handleOrderShow)
	mux.HandleFunc("GET /api/v1/addresses", app.handleAddressesIndex)
	mux.HandleFunc("DELETE /api/v1/addresses/{id}", app.handleAddressDelete)
	mux.HandleFunc("GET /api/v1/favorites", app.handleFavoritesIndex)
	mux.HandleFunc("GET /api/v1/customer/coupons", app.handleCustomerCoupons)
	mux.HandleFunc("GET /api/v1/customer/recent-purchases", app.handleCustomerRecentPurchases)
	mux.HandleFunc("GET /api/v1/customer/loyalty", app.handleCustomerLoyalty)
	mux.HandleFunc("GET /api/v1/customer/recommendations", app.handleCustomerRecommendations)
	mux.HandleFunc("POST /api/v1/orders/{id}/reorder", app.handleOrderReorder)
	mux.HandleFunc("POST /api/v1/favorites/{slug}", app.handleFavoriteAdd)
	mux.HandleFunc("DELETE /api/v1/favorites/{slug}", app.handleFavoriteDelete)
	mux.HandleFunc("GET /api/v1/notifications", app.handleNotifications)
	mux.HandleFunc("POST /api/v1/notifications/read-all", app.handleNotificationReadAll)
	mux.HandleFunc("POST /api/v1/notifications/{id}/read", app.handleNotificationRead)
	mux.HandleFunc("DELETE /api/v1/notifications/{id}", app.handleNotificationDelete)
	mux.HandleFunc("POST /api/v1/notifications/device-tokens", app.handleDeviceToken)
	mux.HandleFunc("DELETE /api/v1/notifications/device-tokens/{token}", app.handleDeviceTokenDelete)
	mux.HandleFunc("GET /api/v1/payments/{id}/status", app.handlePaymentStatus)

	// Mobile-specific ek endpoint'ler
	mux.HandleFunc("POST /api/v1/auth/refresh", app.handleTokenRefresh)
	mux.HandleFunc("POST /api/v1/auth/forgot-password", app.handleForgotPassword)
	mux.HandleFunc("POST /api/v1/auth/reset-password", app.handleResetPassword)
	mux.HandleFunc("POST /api/v1/addresses", app.handleAddressCreate)
	mux.HandleFunc("PATCH /api/v1/addresses/{id}", app.handleAddressUpdate)
	mux.HandleFunc("PUT /api/v1/addresses/{id}", app.handleAddressUpdate)
	mux.HandleFunc("POST /api/v1/addresses/{id}/default", app.handleAddressSetDefault)
	mux.HandleFunc("POST /api/v1/orders/{id}/cancel", app.handleOrderCancel)
	mux.HandleFunc("GET /api/v1/payment-methods", app.handlePaymentMethods)
	mux.HandleFunc("GET /api/v1/branches/nearby", app.handleBranchesNearby)

	mux.Handle("GET /internal/v1/ops/summary", app.internalOnly(http.HandlerFunc(app.handleOpsSummary)))
	mux.Handle("GET /internal/v1/ops/metrics", app.internalOnly(http.HandlerFunc(app.handleRuntimeMetrics)))
	mux.Handle("GET /internal/v1/ops/payment-risk", app.internalOnly(http.HandlerFunc(app.handleOpsPaymentRisk)))
	mux.Handle("GET /internal/v1/ops/mobile", app.internalOnly(http.HandlerFunc(app.handleOpsMobileMonitor)))
	mux.Handle("GET /internal/v1/ops/mobile/devices", app.internalOnly(http.HandlerFunc(app.handleOpsMobileDevices)))
	mux.Handle("GET /internal/v1/ops/mobile/events", app.internalOnly(http.HandlerFunc(app.handleOpsMobileEvents)))
	mux.Handle("GET /internal/v1/ops/queues", app.internalOnly(http.HandlerFunc(app.handleOpsQueues)))
	mux.Handle("POST /internal/v1/ops/cloudflare/purge", app.internalOnly(http.HandlerFunc(app.handleOpsCreatePurge)))

	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		writeError(w, r, http.StatusNotFound, "Endpoint bulunamadı.")
	})

	return app.recover(app.requestID(app.ensureRequestIdentity(app.actionGuard(app.monitor(app.security(app.cors(app.gzip(app.cdnCache(app.maxBody(app.maintenance(app.rateLimit(mux))))))))))))
}
